# task-create-users.yml
---
- name: create user 1
  ansible.builtin.user:
    name: user_1
    password: "{{ user_password | password_hash('sha512') }}"
    groups:
      - wheel
    state: "present"
    shell: "/bin/bash"
    system: false
    create_home: true
    home: "/home/user_1"
  
- name: create user 2
  ansible.builtin.user:
    name: user_2
    password: "{{ user_password | password_hash('sha512') }}"
    groups:
      - wheel
    state: "present"
    shell: "/bin/bash"
    system: false
    create_home: true
    home: "/home/user_2"

- name: create user 3
  ansible.builtin.user:
    name: user_3
    password: "{{ user_password | password_hash('sha512') }}"
    groups:
      - wheel
    state: "present"
    shell: "/bin/bash"
    system: false
    create_home: true
    home: "/home/user_3"
